import{a as w,S as v}from"./assets/vendor-dc8919a4.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const f of s.addedNodes)f.tagName==="LINK"&&f.rel==="modulepreload"&&o(f)}).observe(document,{childList:!0,subtree:!0});function a(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function o(e){if(e.ep)return;e.ep=!0;const s=a(e);fetch(e.href,s)}})();const b="45272340-7dc1a3d2f1c55d3a20037b43c",S="https://pixabay.com/api/";async function m(r,t=1,a=15){const o={key:b,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:a};try{const e=await w.get(S,{params:o});return console.log(e.data),e.data}catch(e){throw console.error("Ошибка при выполнении запроса:",e),e}}function y(r){const t=document.querySelector(".gallery"),a=r.map(o=>`
    <div class="photo-card">
      <a href="${o.largeImageURL}">
        <img src="${o.webformatURL}" alt="${o.tags}" loading="lazy" />
      </a>
      <div class="info">
        <p class="info-item">Likes: ${o.likes}</p>
        <p class="info-item">Views: ${o.views}</p>
        <p class="info-item">Comments: ${o.comments}</p>
        <p class="info-item">Downloads: ${o.downloads}</p>
      </div>
    </div>
  `).join("");t.insertAdjacentHTML("beforeend",a)}function q(){const r=document.querySelector(".gallery");r.innerHTML=""}const x=document.querySelector(".search-form"),l=document.querySelector("#load-more-btn"),h=document.querySelector("#message-box"),p=document.querySelector(".loader");let c="",n=1,i=0,M=15,g=new v(".gallery a");x.addEventListener("submit",O);l.addEventListener("click",P);function L(){p.classList.remove("hidden")}function d(){p.classList.add("hidden")}function u(r){h.textContent=r,h.classList.remove("hidden")}function $(){h.classList.add("hidden")}async function O(r){if(r.preventDefault(),c=r.currentTarget.elements.query.value.trim(),n=1,$(),c!==""){q(),l.classList.add("hidden"),L();try{const t=await m(c,n);if(d(),i=t.totalHits,i===0){u("No images found. Please try another query.");return}y(t.hits),g.refresh(),t.hits.length>0&&n*t.hits.length<i&&l.classList.remove("hidden")}catch{d(),u("An error occurred while fetching images.")}}}async function P(){L(),n++;try{const r=await m(c,n);if(d(),y(r.hits),g.refresh(),n*M>=i){l.classList.add("hidden"),u("We're sorry, but you've reached the end of search results.");return}const{height:t}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}catch{d(),u("An error occurred while fetching more images.")}}
//# sourceMappingURL=commonHelpers.js.map
