import{a as L,S as w}from"./assets/vendor-dc8919a4.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const h of o.addedNodes)h.tagName==="LINK"&&h.rel==="modulepreload"&&i(h)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();const b="45272340-7dc1a3d2f1c55d3a20037b43c",v="https://pixabay.com/api/";async function m(t,r=1,n=15){const i={key:b,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:n};try{const e=await L.get(v,{params:i});return console.log(e.data),e.data}catch(e){throw console.error("Ошибка при выполнении запроса:",e),e}}function y(t){const r=document.querySelector(".gallery"),n=t.map(e=>`
    <div class="photo-card">
      <a href="${e.largeImageURL}">
        <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
      </a>
      <div class="info">
        <p class="info-item">Likes: ${e.likes}</p>
        <p class="info-item">Views: ${e.views}</p>
        <p class="info-item">Comments: ${e.comments}</p>
        <p class="info-item">Downloads: ${e.downloads}</p>
      </div>
    </div>
  `).join("");r.insertAdjacentHTML("beforeend",n),new w(".gallery a").refresh()}function S(){const t=document.querySelector(".gallery");t.innerHTML=""}const q=document.querySelector(".search-form"),l=document.querySelector("#load-more-btn"),f=document.querySelector("#message-box"),g=document.querySelector(".loader");let a="",s=1,c=0;q.addEventListener("submit",M);l.addEventListener("click",$);function p(){g.classList.remove("hidden")}function d(){g.classList.add("hidden")}function u(t){f.textContent=t,f.classList.remove("hidden")}function x(){f.classList.add("hidden")}async function M(t){if(t.preventDefault(),a=t.currentTarget.elements.query.value.trim(),s=1,x(),a!==""){S(),l.classList.add("hidden"),p();try{const r=await m(a,s);if(d(),c=r.totalHits,c===0){u("No images found. Please try another query.");return}y(r.hits),r.hits.length>0&&s*r.hits.length<c&&l.classList.remove("hidden"),s++}catch{d(),u("An error occurred while fetching images.")}}}async function $(){p();try{const t=await m(a,s);if(d(),t.hits.length===0||s*t.hits.length>=c){l.classList.add("hidden"),u("We're sorry, but you've reached the end of search results.");return}y(t.hits),s++;const{height:r}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}catch{d(),u("An error occurred while fetching more images.")}}
//# sourceMappingURL=commonHelpers.js.map
